defaults:
  - _self_
  - model: koopman_ae
  - trainer: default
  - optim: optuna

dataset:
  batch_size: 64
  data_dir: ./data/rabbit_grass_sweeps

save_dirs:
  figures: ./figures
  
wandb:
  project: koopman-control
  mode: disabled